### ISSUE TITLE
Tool crashes when just type `memorify` with no arguments.

### ISSUE THREAD

**Issue by akashraj9828** [design2soft/memorize#1]
If no agruements are passed then it should show an help message and not crash.
I would like to work on this issue. Let me know if youre okay with it.
Thanks.

**Comment by akashraj9828** [comment]
Fix PR opend https://github.com/design2soft/memorize/pull/2

**Comment by madhavmalhotra-3089** [comment]
Ah thanks. Gonna look at it soonish!

Thanks you for taking the effort to fix it up!

**Comment by madhavmalhotra-3089** [comment]
Gonna close this!
